Create `WorkflowExecutionOptions` entity
WoW-2-0-Projects/Feedback.Analyzer pull request #102
Opened 2024-03-12 13:00 UTC by isxoqovxasanboy

2024-03-12 15:34 UTC, sulton-max requested changes
Good job man, just recreate the migrations that's it 👍

2024-03-12 15:34 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Common/Identity/Services/IAccountService.cs
> +        QueryTrackingMode trackingMode = QueryTrackingMode.AsTracking,
Pass `QueryOptions` instead

2024-03-12 15:34 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/WorkflowExecutionOptionRepository.cs
> +public class WorkflowExecutionOptionRepository(AppDbContext dbContext, ICacheBroker cacheBroker)
Add type docs

2024-03-13 06:20 UTC, sulton-max submitted a review, later dismissed
Well done 👏👍

2024-03-13 08:01 UTC, rashidovasadbek approved these changes

2024-03-14 13:59 UTC, sulton-max approved these changes

2024-03-14 14:59 UTC, Ilxom-22 approved these changes

2024-03-14 14:59 UTC, merged