Create `FeedbackAnalysisResult` entity and business logic
WoW-2-0-Projects/Feedback.Analyzer pull request #105
Opened 2024-03-14 10:17 UTC by botirjonabdumannonovv

2024-03-14 14:06 UTC, sulton-max requested changes

2024-03-14 14:06 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/FeedbackAnalysisResults/Mappers/FeedbackAnalysisResultMapper.cs
> +/// </summary>
Remove, don't add docs for mappers and validators

2024-03-14 14:06 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/FeedbackAnalysisResultRepository.cs
> -    }
Why did you remove Create method ? 

Feedback analysis result won't be updated or deleted, but we should definitely be able to create one ))

2024-03-14 14:06 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/FeedbackAnalysisResults/Services/IFeedbackAnalysisResultService.cs
> +}
Add Create method as well

2024-03-15 14:32 UTC, sulton-max submitted a review, later dismissed
Good job 👍

2024-03-15 16:18 UTC, rashidovasadbek approved these changes

2024-03-15 16:21 UTC, isxoqovxasanboy approved these changes

2024-03-15 16:21 UTC, sulton-max approved these changes

2024-03-15 16:21 UTC, merged