Create `FeedbackBatchAnalysisOrchestrationService`
WoW-2-0-Projects/Feedback.Analyzer pull request #122
Opened 2024-03-17 11:02 UTC by Ilxom-22

2024-03-17 11:05 UTC, isxoqovxasanboy approved these changes

2024-03-17 15:29 UTC, sulton-max requested changes

2024-03-17 15:29 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/FeedbackAnalysisWorkflows/EventHandlers/AnalyzeFeedbackEventHandler.cs
> +public class AnalyzeFeedbackEventHandler(IServiceScopeFactory serviceScopeFactory) : IEventHandler<AnalyzeFeedbackEvent>
Add docs

2024-03-17 15:29 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/FeedbackAnalysisWorkflows/EventHandlers/AnalyzeWorkflowFeedbacksEventHandler.cs
> +public class AnalyzeWorkflowFeedbacksEventHandler(IServiceScopeFactory serviceScopeFactory) : IEventHandler<AnalyzeWorkflowFeedbacksEvent>
Add docs

2024-03-17 15:29 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/EntityRepositoryBase.cs
> +            cancellationToken
Remove commented codes

2024-03-18 09:06 UTC, botirjonabdumannonovv submitted a review, later dismissed

2024-03-18 10:06 UTC, sulton-max submitted a review, later dismissed

2024-03-18 10:09 UTC, sulton-max approved these changes
Good job

2024-03-18 11:06 UTC, rashidovasadbek approved these changes

2024-03-18 23:49 UTC, merged