Add client validation for organization CRUD operations
WoW-2-0-Projects/Feedback.Analyzer pull request #146
Opened 2024-03-19 11:16 UTC by isxoqovxasanboy

2024-03-19 11:39 UTC, Ilxom-22 submitted a review, later dismissed

2024-03-19 17:44 UTC, sulton-max requested changes

2024-03-20 07:23 UTC, Ilxom-22 commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/Organizations/Services/OrganizationService.cs
> +            organization.ClientId == clientId && organization.Id == organizationId);
You can put the predicate in the Where() method to the Get() method.

2024-03-20 18:04 UTC, sulton-max requested changes

2024-03-20 18:04 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/Organizations/QueryHandlers/OrganizationGetQueryHandler.cs
> -        organizationGetQuery.Filter.ClientId = requestContextProvider.GetUserId();
No, return this back

2024-03-20 18:04 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/Organizations/Services/OrganizationService.cs
> +
Remove this

2024-03-20 18:04 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/Organizations/Services/OrganizationService.cs
> +
Move this to commad handler

2024-03-20 18:04 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/Organizations/Services/OrganizationService.cs
> +    }
Remove private method for validation

2024-03-22 07:32 UTC, sulton-max requested changes

2024-03-22 07:32 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/Organizations/Services/OrganizationService.cs
>          => organizationRepository.GetByIdAsync(organizationId, queryOptions, cancellationToken);
Add client filter

2024-03-22 07:32 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/Organizations/Services/OrganizationService.cs
> +        return await organizationRepository.DeleteByIdAsync(foundOrganization.Id, commandOptions, cancellationToken);
Add validation

2024-03-23 06:37 UTC, sulton-max approved these changes

2024-03-23 14:25 UTC, merged