Create `Prompts` tab
WoW-2-0-Projects/Feedback.Analyzer pull request #147
Opened 2024-03-19 13:00 UTC by rashidovasadbek

2024-03-19 17:25 UTC, sulton-max requested changes

2024-03-19 17:25 UTC, sulton-max commented on src/Insight.Box.FrontEnd/src/modules/prompts/models/FeedbackAnalysisPromptType.ts
> +    RedactPersonalInformation
Add all prompt categories, except "content safety"

2024-03-20 05:03 UTC, isxoqovxasanboy approved these changes

2024-03-20 05:07 UTC, botirjonabdumannonovv approved these changes

2024-03-20 07:23 UTC, isxoqovxasanboy approved these changes

2024-03-20 07:27 UTC, Ilxom-22 submitted a review, later dismissed

2024-03-20 08:39 UTC, sulton-max approved these changes

2024-03-20 09:00 UTC, isxoqovxasanboy approved these changes

2024-03-20 09:00 UTC, merged