Feature/#1 add common sqrs infratructure
WoW-2-0-Projects/Feedback.Analyzer pull request #18
Opened 2024-02-25 10:57 UTC by botirjonabdumannonovv

Closes #1

2024-02-25 11:49 UTC, sulton-max requested changes

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Common/Queries/IQuery.cs
> +/// </summary>
Change to "Defines"

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastucture/Common/EventBus/Services/EventBusBackgroundService.cs
> +}
Remove

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastucture/Common/EventBus/Services/EventSubscriber.cs
> +}
Remove

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastucture/Common/Settings/EventBusSubscriberSettings.cs
> +    public ushort PrefetchCount { get; set; }
Remove

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Common/Events/IEventHandler.cs
> +/// Marker interface for event handlers.
Change to "Defines"

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Common/Events/Event.cs
> +    public bool Redelivered { get; set; }
Add comments

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Common/Commands/ICommand.cs
> +/// Marker interface for commands.
Change to "Defines"

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Common/EventBus/Services/IAsyncEventBusSubscriber.cs
> +}
Remove

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Common/EventBus/Brokers/IEventSubscriber.cs
> +    ValueTask StopAsync(CancellationToken token);
Remove

2024-02-25 11:49 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/appsettings.Development.json
> +      "PrefetchCount": 1
Remove

2024-02-25 11:51 UTC, bunyodkamalov approved these changes

2024-02-26 05:24 UTC, sulton-max approved these changes
Very well done

2024-02-26 05:24 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastucture/Common/EventBus/Brokers/EventBusBroker.cs
> +public class EventBusBroker(IPublisher mediator) : IEventBusBroker
Add comment

2024-02-26 05:24 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastucture/Common/EventBus/Brokers/EventBusBroker.cs
> +    public ValueTask PublishLocalAsync<TEvent>(TEvent @event) where TEvent : IEvent
Change to `Event`

2024-02-26 05:44 UTC, rashidovasadbek approved these changes

2024-02-26 05:49 UTC, closed without merging