Create Product entity
WoW-2-0-Projects/Feedback.Analyzer pull request #24
Opened 2024-02-26 12:32 UTC by botirjonabdumannonovv

Close: #8

2024-02-26 12:37 UTC, rashidovasadbek approved these changes

2024-02-26 12:46 UTC, isxoqovxasanboy submitted a review, later dismissed

2024-02-26 13:05 UTC, isxoqovxasanboy commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Entities/Product.cs
> +
add summary

2024-02-26 13:24 UTC, sulton-max requested changes

2024-02-26 13:24 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Entities/Product.cs
> +/// Represents a product entity, inheriting auditable properties.
Remove "inheriting auditable properties."

2024-02-26 13:24 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/EntityConfiguration/ProductConfiguration.cs
> +        builder.Property(organization => organization.Description).IsRequired().HasMaxLength(512);
Change lambda variable name to "product"

2024-02-26 13:24 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/Interfaces/IProductRepository.cs
> +/// Represents a repository for managing products.
Change to "Defines"

2024-02-26 13:24 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/ProductRepository.cs
> +/// <param name="dbContext"></param>
Remove params from primary constructors

2024-02-26 13:27 UTC, isxoqovxasanboy submitted a review, later dismissed

2024-02-27 00:29 UTC, sulton-max approved these changes
Good job

2024-02-27 06:20 UTC, bunyodkamalov approved these changes

2024-02-27 06:26 UTC, isxoqovxasanboy approved these changes

2024-02-27 06:35 UTC, merged