Create ` Feedback ` Infrastructure
WoW-2-0-Projects/Feedback.Analyzer pull request #67
Opened 2024-02-29 13:25 UTC by isxoqovxasanboy

2024-03-01 02:01 UTC, bunyodkamalov requested changes

2024-03-02 05:52 UTC, rashidovasadbek commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/Controllers/CustomerFeedbackController.cs
> +    /*[HttpPut]   We don't use it now
remove update endpooints

2024-03-02 05:55 UTC, rashidovasadbek commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/Data/SeedDataExtensions.cs
> +            new CustomerFeedback()
remove type => CustomerFeedback

2024-03-02 05:57 UTC, rashidovasadbek commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/CustomerFeedbacks/Queries/CustomerFeedbackGetQuery.cs
> +    public CustomerFeedbackFilter CustomerFeedbackFilter { get; init; } = default!;
remove init , write set

2024-03-02 06:00 UTC, rashidovasadbek commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/CustomerFeedbacks/CommandHandlers/CustomerFeedbackUpdateCommandHandler.cs
> +            .UpdateAsync(customerFeedback,new CommandOptions(),cancellationToken);
must be inserted before new()

2024-03-02 06:01 UTC, rashidovasadbek commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/CustomerFeedbacks/QueryHandlers/CustomerFeedbackGetByIdQueryHandler.cs
> +    {
must be inserted before CancellationToken

2024-03-02 09:33 UTC, bunyodkamalov commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/CustomerFeedbacks/Queries/CustomerFeedbackGetQuery.cs
> +public class CustomerFeedbackGetQuery : IQuery<ICollection<CustomerFeedbackDto>>
change class to record

2024-03-02 09:36 UTC, sulton-max requested changes

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Clients/Models/ClientFilter.cs
> -
Because we have default values in `FitlerPagination` now

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/CustomerFeedbacks/Commands/CustomerFeedbackDeleteByIdCommand.cs
> +    public Guid ProductId { get; set; }
Add docs

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/CustomerFeedbacks/Commands/CustomerFeedbackUpdateCommand.cs
> +    public CustomerFeedbackDto CustomerFeedback { get; set; } = default!;
Add docs

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/CustomerFeedbacks/Models/CustomerFeedbackDto.cs
> +    public Product Product { get; set; } = default!;
Remove navigation property

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/CustomerFeedbacks/Queries/CustomerFeedbackGetByIdQuery.cs
> +    public Guid ProductId { get; set; } = Guid.Empty;
Add docs

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Organizations/Queries/OrganizationGetByIdQuery.cs
> +    public Guid OrganizationId { get; set; } = Guid.Empty;
Remove empty value initialization

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/CustomerFeedbacks/CommandHandlers/CustomerFeedbackCreateCommandHandler.cs
> +        var createCustomerFeedback =
Rename to `createdCustomerFeedback`

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/CustomerFeedbacks/CommandHandlers/CustomerFeedbackUpdateCommandHandler.cs
> +        var updateCustomerFeedback = await customerFeedbackService
Rename to `updatedCustomerFeedback`

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/CustomerFeedbacks/Mappers/CustomerFeedbackMapper.cs
> +/// </summary>
Remove docs

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/Organizations/Validators/OrganizationValidator.cs
>      {
Remove `ValidationSettings` injection as it's not used

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/CustomerFeedbacks/Validators/CustomerFeedbackValidator.cs
> +    /// </summary>
Remove docs

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/CustomerFeedbacks/Validators/CustomerFeedbackValidator.cs
> +/// </summary>
Remove docs

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/CustomerFeedbacks/Services/CustomerFeedbackService.cs
> +/// Initializes a new instance of the <see cref="CustomerFeedbackService"/> class.
Change `Initializes` to `Represents`

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/Data/SeedDataExtensions.cs
> +        #region Intialize customer feedbacks
Remove region

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/Data/SeedDataExtensions.cs
> +        List<CustomerFeedback> customersFeedbacks =
Use `var`

2024-03-02 09:36 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/Controllers/CustomerFeedbackController.cs
> +        return result is not null ? Ok(result) : NoContent();
Change to `NotFound` result

2024-03-02 09:37 UTC, bunyodkamalov commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/CustomerFeedbacks/CommandHandlers/CustomerFeedbackDeletByIdCommandHandler.cs
> +        await customerFeedbackService.DeleteByIdAsync(request.ProductId, new CommandOptions(), cancellationToken);
add { SkipSaveChanges = false } into `new CommandOptions()`

2024-03-02 09:42 UTC, bunyodkamalov reviewed
Good job

2024-03-03 00:40 UTC, sulton-max approved these changes
Good job

2024-03-03 02:22 UTC, rashidovasadbek approved these changes

2024-03-03 11:00 UTC, bunyodkamalov approved these changes

2024-03-04 03:08 UTC, merged