Feature/#35
WoW-2-0-Projects/Feedback.Analyzer pull request #74
Opened 2024-03-02 05:59 UTC by bunyodkamalov

closes #35

2024-03-02 07:58 UTC, isxoqovxasanboy commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Clients/Mappers/AccessTokenMapper.cs
> +namespace Feedback.Analyzer.Api.Mappers;
## Change namespace:

'False' namespace: Feedback.Analyzer.Api.Mappers;

`True` namespace: Feedback.Analyzer.Application.Clients.Mappers;

2024-03-03 01:26 UTC, sulton-max requested changes

2024-03-03 01:26 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/Common/Identity/Services/IdentitySecurityTokenService.cs
> +    }
Add validation to access token creation method

2024-03-03 01:26 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Common/Settings/RequestUserContextSettings.cs
> +    public Guid SystemUserId { get; set; }
Add docs

2024-03-03 01:26 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Common/Identity/Services/IIdentitySecurityTokenService.cs
> +        bool saveChanges = true,
Use `CommandOptions`

2024-03-03 01:26 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Common/Identity/Services/IIdentitySecurityTokenService.cs
> +        bool saveChanges = true,
Use `CommandOptions`

2024-03-03 01:26 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Clients/Mappers/ClientMapper.cs
> +        CreateMap<Client, SignInDetails>().ReverseMap();
Remove reverse map option

2024-03-03 01:26 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/appsettings.Development.json
> +  },
Move to appsettings instead

2024-03-03 01:26 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/Configurations/HostConfiguration.Extensions.cs
> +        builder.Services.AddSingleton<AccessTokenValidationMiddleware>();
Move to `AddIdentityInfrastructure`

2024-03-03 02:40 UTC, rashidovasadbek commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/Common/Identity/Commands/SignInCommand.cs
> +    public SignInDetails? SignInDetails { get; set; }
must be changed to non-nullable. Remove ? , add defount!

2024-03-03 23:32 UTC, sulton-max approved these changes

2024-03-03 23:32 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/AccessTokenRepository.cs
> +    }
Remove docs from implementation methods

2024-03-03 23:32 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/RefreshTokenRepository.cs
> +public class RefreshTokenRepository(ICacheBroker cacheBroker) : IRefreshTokenRepository
Add type docs

2024-03-04 06:48 UTC, isxoqovxasanboy submitted a review, later dismissed

2024-03-11 12:36 UTC, sulton-max approved these changes
Good job

2024-03-11 12:40 UTC, rashidovasadbek approved these changes

2024-03-11 12:48 UTC, merged