Feature/#44
WoW-2-0-Projects/Feedback.Analyzer pull request #76
Opened 2024-03-02 17:24 UTC by sarvarbek7

OrganizationCard component is added. 
But image url is hardcoded for now

2024-03-03 01:29 UTC, sulton-max requested changes

2024-03-03 01:29 UTC, sulton-max commented on src/Insight.Box.FrontEnd/src/common/views/HomeView.vue
> +import type OrganizationsTabVue from '@/modules/organizations/components/OrganizationsTab.vue';
Remove unnecessary import

2024-03-03 01:29 UTC, sulton-max commented on src/Insight.Box.FrontEnd/src/modules/organizations/components/OrganizationsTab.vue
> +        console.log("Something is wrong");
Remove console log and else block

2024-03-03 02:30 UTC, rashidovasadbek submitted a review, later dismissed

2024-03-03 23:33 UTC, sulton-max submitted a review, later dismissed

2024-03-04 05:51 UTC, Habiba0206 approved these changes

2024-03-04 06:57 UTC, isxoqovxasanboy submitted a review, later dismissed

2024-03-04 14:41 UTC, sulton-max approved these changes

2024-03-04 14:41 UTC, rashidovasadbek approved these changes

2024-03-04 14:48 UTC, Ilxom-22 approved these changes

2024-03-04 14:48 UTC, merged