Create an `AnalysisPromptCategory` entity
WoW-2-0-Projects/Feedback.Analyzer pull request #88
Opened 2024-03-04 15:53 UTC by isxoqovxasanboy

2024-03-04 16:09 UTC, rashidovasadbek submitted a review, later dismissed

2024-03-05 03:55 UTC, botirjonabdumannonovv approved these changes

2024-03-06 07:27 UTC, isxoqovxasanboy reviewed
close #88

2024-03-06 08:17 UTC, rashidovasadbek submitted a review, later dismissed

2024-03-06 10:00 UTC, sulton-max requested changes

2024-03-06 10:00 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Extensions/EnumExtensions.cs
> +    public static string GetDisplayName(this Enum value)
Add docs

2024-03-06 10:00 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/EntityConfiguration/AnalysisPromptCategoryConfiguration.cs
> +            .HasIndex(category => category.Category);
Change to unique index 


Implementation : 

```csharp
builder
         .HasIndex(category => category.Category)
         .IsUnique();
```

2024-03-06 10:00 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/EntityConfiguration/AnalysisPromptCategoryConfiguration.cs
> +            .HasConversion<string>()
Add length constraint for 128 chars

2024-03-06 10:28 UTC, botirjonabdumannonovv approved these changes

2024-03-06 10:29 UTC, rashidovasadbek approved these changes

2024-03-06 11:24 UTC, sulton-max approved these changes
Good job

2024-03-06 11:25 UTC, merged