Create `Analysis Workflow`
WoW-2-0-Projects/Feedback.Analyzer pull request #91
Opened 2024-03-06 12:10 UTC by rashidovasadbek

close: #68

2024-03-06 14:20 UTC, sulton-max requested changes

2024-03-06 14:20 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Enums/WorkflowType.cs
> +    Interface
Change to `Inference`

2024-03-06 14:20 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/EntityConfiguration/AnalysisWorkflowConfiguration.cs
> +        builder.Property(analysisWorkflow => analysisWorkflow.Name).HasMaxLength(128).IsRequired();
Add conversion for `Type` column and add length constraint

2024-03-06 14:20 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/AnalysisWorkflowRepository.cs
> +public class AnalysisWorkflowRepository(AppDbContext appDbContext) : EntityRepositoryBase<AnalysisWorkflow, AppDbContext>(appDbContext), IAnalysisWorkflowRepository
Add type docs

2024-03-06 16:05 UTC, sulton-max requested changes

2024-03-06 16:05 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/EntityConfiguration/AnalysisWorkflowConfiguration.cs
> +        builder.Property(analysisWorkflow => analysisWorkflow.Name).HasMaxLength(128).IsRequired();
Add type conversion and constraint

2024-03-06 16:14 UTC, sulton-max requested changes

2024-03-07 03:08 UTC, sulton-max submitted a review, later dismissed
Good job 👍👏

2024-03-07 04:57 UTC, isxoqovxasanboy approved these changes

2024-03-07 06:13 UTC, sulton-max approved these changes

2024-03-07 06:13 UTC, botirjonabdumannonovv approved these changes

2024-03-07 06:13 UTC, botirjonabdumannonovv commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/EntityConfiguration/AnalysisWorkflowConfiguration.cs
> +            .IsRequired();
remove unnecessary row

2024-03-08 12:35 UTC, sulton-max requested changes

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Entities/AnalysisWorkflow.cs
> +    public FeedbackAnalysisWorkflow FeedbackAnalysisWorkflow = default!;
Remove navigation

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Domain/Entities/FeedbackAnalysisWorkflow.cs
> +    public Product Product { get; set; } = default!;
Add docs

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/Controllers/AnalysisWorkflowController.cs
> + }
Remove this controller

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/AnalysisWorkflows/Commands/AnalysisWorkflowCreateCommand.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/AnalysisWorkflows/Commands/AnalysisWorkflowDeleteByIdCommand.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/AnalysisWorkflows/Commands/AnalysisWorkflowUpdateCommand.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/AnalysisWorkflows/Models/AnalysisWorkflowDto.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/AnalysisWorkflows/Queries/AnalysisWorkflowGetByIdQuery.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Application/AnalysisWorkflows/Queries/AnalysisWorkflowGetQuery.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/AnalysisWorkflows/CommandHandlers/AnalysisWorkflowCreateCommandHandler.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/AnalysisWorkflows/CommandHandlers/AnalysisWorkflowDeleteByIdCommandHandler.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/AnalysisWorkflows/CommandHandlers/AnalysisWorkflowUpdateCommandHandler.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/AnalysisWorkflows/Mappers/AnalysisWorkflowMapper.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/AnalysisWorkflows/QueryHandlers/AnalysisWorkflowGetByIdQueryHandler.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Infrastructure/AnalysisWorkflows/QueryHandlers/AnalysisWorkflowGetQuery.cs
> +}
Remove

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/EntityConfiguration/FeedbackAnalysisWorkflowConfiguration.cs
> +        ).IsUnique();
Remove this and add 

"TODO : Add name and product Id unique index between this and `AnalysisWorkflow` tables"

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/Interfaces/IFeedbackAnalysisWorkflowRepository.cs
> +public interface IFeedbackAnalysisWorkflowRepository
Add type docs

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Repositories/FeedbackAnalysisWorkflowRepository.cs
> +public class FeedbackAnalysisWorkflowRepository(AppDbContext appDbContext)
Add type docs

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Migrations/20240308062843_Add FeedbackAnalysisWorkflow_And_AnalysisWorkflow.cs
> +                    Name = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
Remove name prop

2024-03-08 12:35 UTC, sulton-max commented on src/Feedback.Analyzer.Backend/Feedback.Analyzer.Persistence/Migrations/20240308062843_Add FeedbackAnalysisWorkflow_And_AnalysisWorkflow.cs
> +                    Type = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false)
Remove type prop

2024-03-08 14:44 UTC, sulton-max approved these changes
Good job 👏

2024-03-08 14:46 UTC, botirjonabdumannonovv approved these changes

2024-03-08 14:49 UTC, isxoqovxasanboy approved these changes

2024-03-08 14:50 UTC, merged